# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='venues', verbose_name='cover'),
        ),
        migrations.AddField(
            model_name='venue',
            name='rectangle',
            field=image_cropping.fields.ImageRatioField('cover', '1200x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='rectangle'),
        ),
    ]
