# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20170217_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='show_assists',
            field=models.BooleanField(default=False, verbose_name='show assists stats'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='show_card',
            field=models.BooleanField(default=False, verbose_name='show card stats'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='show_goal',
            field=models.BooleanField(default=False, verbose_name='show goal stats'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='show_league',
            field=models.BooleanField(default=False, verbose_name='show league tables'),
        ),
        migrations.AlterField(
            model_name='match',
            name='go_extra',
            field=models.BooleanField(default=False, verbose_name='go to extra time'),
        ),
        migrations.AlterField(
            model_name='match',
            name='has_extra',
            field=models.BooleanField(default=False, verbose_name='extra time has happened'),
        ),
        migrations.AlterField(
            model_name='match',
            name='is_result',
            field=models.BooleanField(default=False, verbose_name='is result'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='after_extra',
            field=models.BooleanField(default=False, verbose_name='After extra time'),
        ),
        migrations.AlterField(
            model_name='round',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='round',
            name='has_assists',
            field=models.BooleanField(default=False, verbose_name='has assists stats'),
        ),
        migrations.AlterField(
            model_name='round',
            name='has_card',
            field=models.BooleanField(default=False, verbose_name='has card stats'),
        ),
        migrations.AlterField(
            model_name='round',
            name='has_goal',
            field=models.BooleanField(default=False, verbose_name='has goal stats'),
        ),
        migrations.AlterField(
            model_name='round',
            name='has_league',
            field=models.BooleanField(default=False, verbose_name='has league tables'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_national',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='team',
            name='show_assists',
            field=models.BooleanField(default=False, verbose_name='show assists stats'),
        ),
        migrations.AlterField(
            model_name='team',
            name='show_card',
            field=models.BooleanField(default=False, verbose_name='show card stats'),
        ),
        migrations.AlterField(
            model_name='team',
            name='show_goal',
            field=models.BooleanField(default=False, verbose_name='show goal stats'),
        ),
        migrations.AlterField(
            model_name='team',
            name='show_league',
            field=models.BooleanField(default=False, verbose_name='show league tables'),
        ),
    ]
