# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0004_auto_20170217_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured_article', to='stats.Match')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
                'verbose_name': 'featured match',
            },
        ),
    ]
