# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tote', '0005_auto_20170406_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='category',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Limited')], default=1, verbose_name='Tournament type'),
        ),
    ]
